### ISSUE TITLE
ARI 1.7.0 - Language Field Return in Channel using Asterisk 13.1 Certified 

### ISSUE THREAD

**Issue by pta200** [l3nz/ari4java#28]
Getting the following exception when running the following code. Seems language is now a property returned in the ARI channel. I will see about editing the channels.json file to add the property and see if works.

Map<String, String> orVar = new HashMap<String, String>();
Channel chan =  ari.channels().originate("SIP/" + message.get("origin"), "", "", new Long(1), "bridge-dial", "inbound", message.get("destination"), 30, orVar, "", "");

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "language" (class ch.loway.oss.ari4java.generated.ari_1_6_0.models.Channel_impl_ari_1_6_0), not marked as ignorable (8 known properties: , "state", "connected", "dialplan", "accountcode", "caller", "name", "id", "creationtime"]) at [Source: java.io.StringReader@1ac9004; line: 20, column: 16] (through reference chain: ch.loway.oss.ari4java.generated.ari_1_6_0.models.Channel_impl_ari_1_6_0["language"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
        at ch.loway.oss.ari4java.tools.BaseAriAction.deserializeJson(BaseAriAction.java:240)
        at ch.loway.oss.ari4java.generated.ari_1_6_0.actions.ActionChannels_impl_ari_1_6_0.originate(ActionChannels_impl_ari_1_6_0.java:79)

**Comment by pta200** [comment]
Per the documentation I can't generate the java code from channels.json so not sure how to do it, but for a test I added get/set methods for the language property to the 1.6 implementation and that solved the problem.

**Comment by l3nz** [comment]
Which version of ARI is your Asterisk returning? as the classi s generated out of the JSON descriptors, looks weird it being there.....

**Comment by l3nz** [comment]
Look here: https://github.com/l3nz/ari4java/blob/master/codegen-data/ari_1_6_0/channels.json - the Channel object is the last one by the bottom of the file and it does not have a "language".

**Comment by pta200** [comment]
Yes I found that and edited my local copy, but how do I run the code generator? According to README gradle build doesn't do include code gen. I figured I'm missing something so for testing I just edited the java file.

**Comment by l3nz** [comment]
But is the ARI version set to 1.6.0 or is it a newer version? because if there is a newer version out, I will rebuild the library for everybody.

**Comment by l3nz** [comment]
I was able to rebuild version 0.3.0 as I noticed that in Asterisk 13.2.0 there is ARI 1.7.0.

**Comment by amitlattyan** [comment]
I am New using ARI. Please tell me how to play prompt and taking DTMF input using ari4java. I am
<a href="http://www.globalbinarytech.com/" rel="dofollow">Amit</a>
