### ISSUE TITLE
JsonMappingException

### ISSUE THREAD

**Issue by jnk111** [l3nz/ari4java#67]
Hello,

i always get the following stacktrace (on receiving events):

```
com.fasterxml.jackson.databind.JsonMappingException: Method availble from ... (through reference chain: ch.loway.oss.ari4java.generated.ari_1_10_0.models.ChannelVarset_impl_ari_1_10_0["asterisk_id"])
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:510)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:493)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:116)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:157)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:123)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:82)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:894)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:36)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at ch.loway.oss.ari4java.tools.BaseAriAction.deserializeJson(BaseAriAction.java:132)
	at ch.loway.oss.ari4java.tools.AriAsyncHandler.handleResponse(AriAsyncHandler.java:37)
	at ch.loway.oss.ari4java.tools.AriAsyncHandler.onSuccess(AriAsyncHandler.java:65)
	at ch.loway.oss.ari4java.tools.http.NettyWSClientHandler.channelRead0(NettyWSClientHandler.java:90)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Method availble from ...
	at ch.loway.oss.ari4java.generated.ari_1_10_0.models.Message_impl_ari_1_10_0.setAsterisk_id(Message_impl_ari_1_10_0.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:114)
	... 32 more
No!
```
It seems to be a json mapping problem.
I am using Asterisk 13.15.1 with ARI-API-Version 1.10.0 and ari4java 0.4.4, running with the following Code:

```
public class ARITest {

	public static void main(String[] args) throws ARIException, URISyntaxException {
		
		ARI ari = AriFactory.nettyHttp("http://192.168.178.27:8088/", "asterisk", "asterisk", 
		        AriVersion.ARI_1_10_0);
		
		ActionEvents events = ari.events();
		events.eventWebsocket("hello-world", true, new AriCallback<Message>() {
			
	        @Override
	        public void onSuccess(Message result) {
	        	System.out.println("Yes! " + result);
	        }

	        @Override
	        public void onFailure(RestException e) {
	        	System.out.println("No! " );
	        }
	});
	}
}
```

Are there any ideas how to fix this?

**Comment by jnk111** [comment]
ok, with asterisk version 13.7.0 it's working

**Comment by l3nz** [comment]
Yes: if you look at the trace, it says:

     java.lang.UnsupportedOperationException: Method availble from ...
    at .setAsterisk_id()

So it is saying calling `setAsteriskId()` is not supported on the version of ARI that you are using to talk to Asterisk.
