### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by chongzilla** [l3nz/ari4java#95]
**Hi,
I have a stock version of Asterisk 12.8.2 running on RHEL 6.9.  I'm trying to run the HelloAriWorld.java, but I'm getting:**
Hello ARI world!
java.net.ConnectException: Connection refused: /192.168.1.102:8088
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)

**The server is running on 192.168.1.102.**

**The part failing is this:**
ARI ari = AriFactory.nettyHttp("http://192.168.1.102:8088/", "ari4java", "yothere", AriVersion.ARI_1_5_0);

**In ari.conf I have this:**
[general]
enabled = yes

[ari4java]
type = user
read_only = no
password = yothere
password_format = plain

**In http.conf I have this:**
[general]
enabled=yes
bindaddr=192.168.1.102
bindport=8088

**When I show ari users, I get:**
r/o?  Username
----  --------
No    ari4java

What am I doing wrong to connect here?  (I tried 127.0.0.1 too)
I just want to get this working so that I can connect and get a list of calls/channels and conference rooms.

Thanks,
Stan

**Comment by NaamaGertel** [comment]
Your http.conf and ari.conf looks fine. You also need to have an extensions.conf file which define the dialplan, that will connect between the stasis application to the websocket, meaning the websocket will listen to ARI events for the specified application. for example:

[dialplan-application-activate]
exten => _X.,1,Noop(**** Activating Dialplan application for CLID: ${CALLERID(num)} ****)
 same =>    n,Stasis(myStasisApp)
 same =>     n,Hangup()

You have an explanation about the files here:
https://wiki.asterisk.org/wiki/display/AST/Getting+Started+with+ARI

Regarding the 'Connection refused' problem, Try to create an ari instance with:
ARI ari = ARI.build(http://192.168.1.102:8088/, "myStasisApp", "ari4java", "yothere", AriVersion.ARI_1_5_0);
Note that "myStasisApp" is the name of the stasis application defined in the dialplan.
